image: docker.vokal.io/web-testing
env:
    - BOWER_LOGIN=$$bowerLogin
    - BOWER_OAUTH=$$bowerOauth
    - CVR_TOKEN=$$cvrToken
script:
    - echo "machine github.com" > ~/.netrc
    - echo "login $BOWER_LOGIN" >> ~/.netrc
    - echo "password $BOWER_OAUTH" >> ~/.netrc
    - git config --global url."https://github".insteadOf git://github
    - npm install -g istanbul
    - npm install
    - chmod +x run-build.sh
    - ./run-build.sh
notify:
    webhook:
        urls:
            - https://dronebot.vokalinteractive.com/hook
        on_success: true
        on_failure: true
